### PR TITLE
Development reportweather feature

### PR DESCRIPTION
**Pull request by vikrantdeshpande09876**
Assigning @shubhpatr and @RutujaJadhav19 as reviewers for completed build of Flask microservices.
Please refer to README.md in feature-branch for usage-documentation.

### CODE REVIEW

**Comment by shubhpatr** [comment]
Minor Issue, 

Some of the dependencies were commented out, and scipy version needs to be 1.6.1

**Comment by vikrantdeshpande09876** [comment]
Updated codebase as per suggestions and latest discussions to merge `radar-stations` microservice functionality into this `report-weather` microservice itself.
@shubhpatr , @RutujaJadhav19 - Next steps: merge this pull request after meeting on 4th Feb 2022.

**Comment by vikrantdeshpande09876** [comment]
Need to change `docker-compose.yml` for #38 and #32.
Adding docker-network for consistency.

**Comment by shubhpatr** [comment]
Checked and integrated, works well!

**Review by shubhpatr — APPROVED** [review]
lgtm!

**Comment by vikrantdeshpande09876** [comment]
Merged manually from local CLI due to conflicts.

**Pull request closed without merging**
